### ISSUE TITLE
deployed versions of v6.js are not consistent

### ISSUE THREAD

**Issue by JoshRagem** [pnpm/get#1]
when trying to download from https://get.pnpm.io/v6.js we have sometimes struggled to get consistent sha sums; we get either of:

* `cb3008849965fdb6c9b6101186ae1234d6600d56eb16b5817e72269cf15f2efa`
* `66e6909849e1c7f0ba9aa5055f0cbc91c776379cb05d7dea796e319cc2cd26f5`

which does not provide good confidence that the sum or the signature for it are valid or even match (even from the same machine, I have gotten non-matching values for the signature)

there is no deployment code in this repo, but it seems the logical place to make a ticket

**Comment by zkochan** [comment]
I don't understand how it can be possible. Seems like the old version is cached somewhere.

Could you try downloading with a query?
```
https://get.pnpm.io/v6.js?1
```

**Comment by JoshRagem** [comment]
that one got me `66e6909849e1c7f0ba9aa5055f0cbc91c776379cb05d7dea796e319cc2cd26f5` this time

> I don't understand how it can be possible

definitely got an old version cached someplace. actually, I was pretty sure this happened before (when I had to switch from `cb3...` to `66e...`) but I didn't have as good evidence as I did today

**Comment by zkochan** [comment]
Well, I will have to upload a new file then because I tried to reset cache a lot of times and this is reported not the first time.

**Comment by zkochan** [comment]
I have uploaded a new file, try with it: https://get.pnpm.io/v6.6.js
